version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: pdoc3
    versions:
    - "> 0.7.0, < 0.8"
  - dependency-name: pdoc3
    versions:
    - ">= 0.7.a, < 0.8"
