# Usage:
# docker-compose build && docker-compose up
version: '2'

services:
  grocy-nginx:
    image: grocy/nginx:v2.7.1-2
    depends_on:
      - grocy
    ports:
      - '80:80'
      - '443:443'
    volumes_from:
      - grocy
    container_name: grocy-nginx

  grocy:
    image: grocy/grocy:v2.7.1-2
    expose:
      - 9000
    volumes:
      - database:/www
    environment:
      PHP_MEMORY_LIMIT:    512M
      MAX_UPLOAD:          50M
      PHP_MAX_FILE_UPLOAD: 200
      PHP_MAX_POST:        100M
      GROCY_CULTURE: en
      GROCY_MODE: demo
    container_name: grocy
volumes:
  database:
